QuEST-Kit/QuEST

QuEST/CPU/QuEST_cpu.c
QuEST/CPU/QuEST_cpu_distributed.c
QuEST/CPU/QuEST_cpu_internal.h
QuEST/CPU/QuEST_cpu_local.c
QuEST/GPU/QuEST_gpu.cu
QuEST/QuEST.c
QuEST/QuEST.h
QuEST/QuEST_common.c
QuEST/QuEST_internal.h
QuEST/QuEST_ops.h
QuEST/QuEST_validation.c
QuEST/QuEST_validation.h
makefile
tests/runTests.sh

Previously, the hardware-specific backend code was littered with `QuESTAssert`s which didn't do more than validate user input. Error messages were id'd by their index in a list of strings. This meant...
- enormous code duplication, both between backend files, and functions which perform similar validation
- invalid input would be reported to have occured in an internel function the user didn't directly call
- anonymous numbers all over the place (passed error message ids)
- compiler can't detect invalid error message id
- developer can't recognise incorrect error message id
To fix all of these, user input validation is now centralised into QuEST_validation, which is invoked exclusively by QuEST (which resolves the API). Error messages are id'd by enums with meaningful names (e.g. …

Centralising validation

---

QuEST/src/CPU/QuEST_cpu_distributed.c

This caused intermittent errors that occur with certain seed values, and were not caught by testing

mpi version of seeding function used wrong data type. 

---

QuEST/CPU/QuEST_cpu_distributed.c

This caused intermittent errors that occur with certain seed values, and were not caught by testing
Same bug fix as submitted to develop. Suggest we pull this into master now without waiting until we pull this and all the other changes made in develop into master, as in the wrong circumstances this will cause the current version of master to crash in mpi mode

mpi version of seeding function used wrong data type.

---

QuEST/CMakeLists.txt

changed build system so that if no CMAKE_BUILD_TYPE is specified, optimisation level defaults to -O2
Addresses issue #111

Issue #111

---

QuEST/include/QuEST.h
QuEST/src/CPU/QuEST_cpu_distributed.c
QuEST/src/CPU/QuEST_cpu_local.c
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/QuEST_common.c
QuEST/src/QuEST_debug.h
examples/README.md

Default seeding is now done only by pid and time.
hostname seeding removed as it is messy to implement across windows and linux consistently.
Removing hostname seeding will only be a problem if two QuEST programs are launched on different nodes at the same millisecond and are assigned the same pid, therefore keeping it doesn't seem worth the cross platform compilation difficulty.
Nevertheless this change of behaviour should be noted in future releases. 
This addresses issue #23 as well as reports from an external user that the code did not compile on windows using mingw.

Removed seeding by hostname from seedQuESTDefault.

---

examples/makefile

Moved makefile to examples folder to prevent confusion between this makefile and that generated by the new cmake build system in the build folder. examples/makefile should only be used as a backup if the cmake system doesn't work on a particular system.
Added tutorial_example.c to root folder

Updated makefile for new file structure, based on PR #117 updates.

---

QuEST/src/CPU/QuEST_cpu.c
QuEST/src/CPU/QuEST_cpu_distributed.c

Maths was not quite right in the distributed version. Also needed to account for the fact that in the distributed version sometimes we are operating on upper and sometimes on lower halves of a block, and there is a sign difference in how they are updated. This is handled by passing through (-1)xconjFac in the case of lower halves of a block.

fixed bug in distributed version of controlledPauliY

---

utilities/QuESTTest/QuESTCore.py

Reorder print unpacking to fix for pre PEP-448 unpacking syntax.

Fix #174 for Python 3.4

---

QuEST/include/QuEST.h
QuEST/src/QuEST_validation.c

to allow user-overriding of QuEST's invalid-input handling, such as via throwing C++ exceptions. 
See issue #186

added invalidQuESTInputError

---

QuEST/CMakeLists.txt

Prevented error seen in #148 on passing c flags through -Xcompiler. As far as I can tell these are not strictly required as the c compiler is still receiving them. Should investigate why CMAKE_C_FLAGS and not CMAKE_CXX_FLAGS are being passed through to compile a c++ file
-- now branched from dev, not master

prevented error on passing c flags through -Xcompiler. 

---

QuEST/src/QuEST_validation.c
tests/test_data_structures.cpp

* Added `UL` type literal for calculating `numAmps` in `validateNumQubitsInQureg`. The existing implementation caused an overflow, leading to `E_DISTRIB_QUREG_TOO_SMALL` even when `2^numQubits >= numRanks`.
* Modified the `number of amplitudes` section in `createQureg` and `createDensityQureg` tests to check for up to 64 numQubits.

Fix overflow issues in validateNumQubitsInQureg

---

QuEST/CMakeLists.txt

Changing target_compile_definitions to public so that they are inherited by the user circuit file

Bug fix of issue #236

---

QuEST/CMakeLists.txt

Compiling on macOS with OpenMP enabled and installed fails due to a missing `target_link_libraries(...)` in the `CMakeLists.txt`.
This isn't picked up by the CI as the tests don't have OpenMP installed. To demonstrate the issue and fix, I have a branch with actions that show the compile errors:
Before fix: https://github.com/drewsilcock/QuEST/runs/533841934?check_suite_focus=true
After fix: https://github.com/drewsilcock/QuEST/runs/533846020?check_suite_focus=true

Bugfix: fix macOS OpenMP linker errors

---

QuEST/CMakeLists.txt
QuEST/include/QuEST.h
QuEST/src/CPU/QuEST_cpu.c
QuEST/src/CPU/QuEST_cpu_distributed.c
QuEST/src/CPU/QuEST_cpu_internal.h
QuEST/src/CPU/QuEST_cpu_local.c
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/QuEST.c
QuEST/src/QuEST_internal.h
QuEST/src/QuEST_validation.c
QuEST/src/QuEST_validation.h
tests/test_calculations.cpp
tests/test_data_structures.cpp
tests/test_operators.cpp
tests/test_state_initialisations.cpp
tests/test_unitaries.cpp
tests/utilities.cpp
tests/utilities.hpp

unit testing passed for:
- serial (MacOS)
- multithreaded and distributed (Ubuntu, for `2`, `4`, `8` and `16` nodes)
- GPU (Ubuntu, Quadro P5000)

added support for efficient diagonal operators

---

QuEST/CMakeLists.txt

In [QuEST/CMakeLists.txt:138](https://github.com/QuEST-Kit/QuEST/blob/c8b954abd1fd0a9f1a2e8fb98efed700f2ff75bf/QuEST/CMakeLists.txt#L138) when `MULTITHREADED` is set to 0 due to the version being too low, the library will still be attempted to be linked in [QuEST/CMakeLists.txt:322](https://github.com/QuEST-Kit/QuEST/blob/c8b954abd1fd0a9f1a2e8fb98efed700f2ff75bf/QuEST/CMakeLists.txt#L322).
We can simply check for both OPENMP_FOUND and MULTITHREADED before linking OpenMP.

OpenMP version mismatch will still lead to an attempted link

---

CMakeLists.txt

This fixes the bug described in #129 in cmake in https://gitlab.kitware.com/cmake/cmake/-/issues/14201 where cuda_add_library would not pick up the include files as given by target_include_directories.
This was fixed in this [commit](https://gitlab.kitware.com/cmake/cmake/-/commit/7ded655f7ba82ea72a82d0555449f2df5ef38594) which first made it into cmake version 3.7, and therefore this fix simply increases our required cmake version.

Update required cmake version to 3.7

---

QuEST/CMakeLists.txt

Modified QuEST/CMakeLists.txt to suppress warnings and make it useful for a standalone library building.

Cmake warnings

---

QuEST/include/QuEST.h
QuEST/src/CPU/QuEST_cpu.c
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/QuEST_qasm.c
QuEST/src/QuEST_validation.c
tests/test_operators.cpp

The functions `applyParamNamedPhaseFunc()` and `applyParamNamedPhaseFuncOverrides()` now accept the new function types `SCALED_INVERSE_SHIFTED_NORM` and `SCALED_INVERSE_SHIFTED_DISTANCE`, which work in much the same way as the already implemented `SCALED_INVERSE_NORM` and `SCALED_INVERSE_DISTANCE`, but add a constant value to each of the sub-registers (or pairs of sub-registers) before calculating the norm and distance, respectively.

Phase functions with shift

---

QuEST/include/QuEST.h
QuEST/src/CPU/QuEST_cpu.c
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/QuEST.c
QuEST/src/QuEST_common.c
QuEST/src/QuEST_internal.h
tests/test_operators.cpp

- enabled passing density matrices to functions `applyPhaseFunc()`, `applyPhaseFuncOverrides()`, `applyMultiVarPhaseFunc()`, `applyMultiVarPhaseFuncOverrides()`, `applyNamedPhaseFunc()`, `applyNamedPhaseFuncOverrides()`, `applyParamNamedPhaseFunc()` and `applyParamNamedPhaseFuncOverrides()`
- added density matrix unit tests for above
- patched insidious memory-initialisation GPU bug in multi-register versions of above, not triggered by state-vector unit tests since they allocated insufficient GPU memory. Scary!

adapted phase functions for density matrices

---

QuEST/src/QuEST_validation.c

previously, it couldn't be overriden in the user's code, since it was not weakly linked (a gcc feature).
Now, it leverages an undocumented 'altername' MSVC pragma to achieve the same result (tested with QuESTlink) in a platform-agnostic way

patched invalidQuESTInputError for MSVC build

---

QuEST/include/QuEST.h
QuEST/src/CPU/QuEST_cpu.c
QuEST/src/GPU/QuEST_gpu.cu
tests/test_operators.cpp

which slightly differed to documentation.
- Previously, SCALED_INVERSE_SHIFTED_DISTANCE computed coeff/sqrt( (x2-x1-dx)^2 + ... ), but now computes coeff/sqrt( (x1-x2-dx)^2 + ... (x1 and x2 have swapped)
- Previously, SCALED_INVERSE_SHIFTED_NORM and SCALED_INVERSE_SHIFTED_DISTANCE used their divergence parameter when their denominators were precisely zero. Now, the divergence parameter is used whenever the denominator is within REAL_EPS to zero.

patched shifted phase functions

---

README.md

Current deprecated badge (chosen for its consistency with other bagde styles) is incorrectly showing 'fail' despite all CI passing.

temporary CI badge patch

---

QuEST/src/QuEST_validation.c

Compilation for x86 on Windows prefixes exported C functions with an underscore, while x64 does not. This is important for the weak symbol `invalidQuESTInputError`, which for Windows is realised through the `alternatename` pragma linker comment. This commit implements different pragmas for win32 and win64, one with and one without name mangling.

Win32 compatibility

---

QuEST/CMakeLists.txt

This PR addresses two issues:
1. The current configuration blocks C and C++ flags from automatically being propagated through to the compiler by nvcc via `-Xcompiler`. This makes it unnecessarily complicated to pass flags like `-fPIC` to the compiler in GPU accelerated mode. There is a comment in the code complaining that the wrong flags were passed through (C flags to C++ compilers), but in the current version this problem could not be reproduced, despite testing compilation of a `.cpp` user source file with cmake 3.7.0 (minimum supported) and 3.22rc2 (most recent) on
- Ubuntu 20.04.3 with GCC 8.4.0 and nvcc 10.1.243
- macOS 10.13.6 with Clang 3.9.1 and nvcc 10.0.130
- Windows 10.0.19043.928 with MSVC 14.29.30133 and nvcc 11.5.50
It therefore seems safe to re-enable automatic flag …

Improve usability as library

---

QuEST/src/CPU/QuEST_cpu.c
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/QuEST.c
QuEST/src/QuEST_common.c
QuEST/src/QuEST_qasm.c
examples/bernstein_vazirani_circuit.c
examples/grovers_search.c
examples/tutorial_example.c

For precision agnosticism, QuEST provides macros for format specifiers and function calls in `QuEST_precision.h`, which should be used in place of hard-coded `%f` and the like, as well as calls to `fabs()`. This PR replaces instances of such specific function calls and string formats with their precision-agonstic equivalent.

Improve precision agnosticism

---

QuEST/src/CPU/QuEST_cpu.c
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/QuEST_qasm.c
QuEST/src/QuEST_validation.c
QuEST/src/QuEST_validation.h

For most cases, when QuEST receives invalid input, it will exit through the overridable function `invalidQuESTInputError()`. In some instances, however, QuEST calls `exit(1)` directly and immediately kills the process. This is undesirable if it is running as part of a larger application, because it prevents printing tracebacks by the parent process (as is the case e.g. for pyQuEST in Python).
This PR seeks to funnel _all_ calls to `exit()` through `invalidQuESTInputError`, in an effort to never exit QuEST unexpectedly and always give the user the option to detect when something has gone wrong and act accordingly.
There are valid points to be raised about the design approach used. The exit-gateway function `invalidQuESTInputError` mentions an invalid input and thus hints at user error, …

Prevent hard exit

---

QuEST/include/QuEST_precision.h

Even though qreal can be represented by long double (if PRECISION=4), the arithmetic and trigonometric operations performed cast the value to double. This is a simple fix.

Fix long double operations

---

QuEST/CMakeLists.txt
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/GPU/cuda_to_hip.h
examples/README.md

This pull request includes lightweight modification to support the use of HIP to run on AM GPUs when GPUACCELERATED=1.
I added brief instructions on how to compile with HIP in the "Compile for GPUs" section of the tutorial.
After my additions, all the tests from the unit testing passed when running on an AMD GPU.
I hope this is useful.

Support for AMD GPUs 

---

tests/test_decoherence.cpp
tests/test_operators.cpp
tests/test_unitaries.cpp
tests/utilities.cpp
tests/utilities.hpp

Before each unit test, the initial state of the registers (assumed to be in the result of initDebugState) is now explicitly checked.
This prevents passing tests when initDebugState() itself is failing, and (for example) yielding an all-zero state which sneakily satisfies some unit tests.
This will likely noticeably increase the total unit-tests runtime, but will gaurantee tests visibly, instantly fail when (for example) the GPU configuration is wrong and produces all-zero states

added unit-test init-state check

---

QuEST/src/GPU/QuEST_cuQuantum.cu

Added all decoherence channels which can be directly mapped (without unacceptable performance damage) to a cuQuantum call.
The cuQuantum calls are:
- custatevecApplyMatrix
- custatevecApplyGeneralizedPermutationMatrix
and are called with matrices (some, diagonal) describing the channel superoperators.
The remaining decoherence channels require linearly combining device vectors (may use Thrust), bespoke GPU kernels, or a clever decomposition of the channel (e.g. 2 qubit depolarising) into a sequence of cuStateVec calls

added wrapped decoherence

---

QuEST/src/GPU/QuEST_cuQuantum.cu
QuEST/src/GPU/QuEST_gpu.cu
QuEST/src/GPU/QuEST_gpu_common.cu

which involved moving `mixTwoQubitDepolarising` into `QuEST_gpu_common.cu`

added bespoke decoherence

---

QuEST/src/CPU/QuEST_cpu_distributed.c

The function `exchangeStateVectors` was modified to take advantage of non-blocking MPI communication. 
Currently, QuEST uses blocking communication calls to exchange the statevector in chunks of 2GB. On large systems, which feature high memory and a fast interconnect, this caused a noticeable slowdown. By changing the communication to non-blocking, up to 10% speedup was achieved on ARCHER2, as described in the following paper: [https://arxiv.org/abs/2308.07402](https://arxiv.org/abs/2308.07402). 
Ideally the request array would not be allocated and freed in this function, however, placing it elsewhere would require introducing MPI headers in areas of the code in which they are not currently required, for example in QuESTEnv.

Made MPI calls in exchangeStateVectors non-blocking

---

QuEST/src/GPU/QuEST_cuQuantum.cu
QuEST/src/QuEST_validation.c
tests/test_decoherence.cpp
tests/utilities.cpp

Previously, the random unitaries used by unit tests were generated through direct Gram-Schmidt orthonormalisation of the rows of random complex matrices. This was numerically unstable, often leading to non-negligibly non-unitary matrices which were then replaced with the identity matrix as a last resort.
Now, the random unitaries are produced by QR decomposition (leveraging the existing Gram-Schmidt orthonormalisation), and the prescription at pg 11 of [this work](https://arxiv.org/pdf/math-ph/0609050.pdf). This is significantly more stable - the identity failsafe is now completely removed - and better tests the API functions which require unitaries and Kraus maps.

improved getRandomUnitary in testing

---

quest/include/environment.h
quest/include/qureg.h
quest/src/api/environment.cpp
quest/src/api/qureg.cpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

replacing...
- `QuESTEnv createQuESTEnv()`
- `void destroyQuESTEnv(QuESTEnv env)`
with (yes, using US spelling...)
- `void initQuESTEnv()`
- `void finalizeQuESTEnv()`
All other functions which received `QuESTEnv` as an argument, now do not. 
Also added
- `QuESTEnv getQuESTEnv()`
to get a copy of the internal `QuESTEnv` single instance, which may be useful for stacks or debugging.

made QuESTEnv a singleton

---

quest/include/structures.h
quest/include/wrappers.h
quest/src/api/qureg.cpp
quest/src/api/structures.cpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp
quest/src/gpu/gpu_config.cpp
quest/src/gpu/gpu_config.hpp
scripts/compile.sh

which required bumping up the user's C standard from C99 to C11 (in order to make use of _Generic)
Remaining changes needed:
- test initialisers with ~~GNU and~~ dreaded MSVC
- add CompMatrN parsing from string (to complete C's setLiteralCompMatrN)
- update matrix-is-unitary validation to use hardware acceleration, depending on size, and whether matrix has persistent GPU memory
- add example files of all the wonderful initialisation paradigms now possible
Those preprocessors are _gruesome_

added CompMatr initialisers

---

quest/include/structures.h
quest/src/api/structures.cpp

- renamed `*Literal*` to `*Inline*` to better reflect that functions like `getInlineCompMatrN` (formerly `getLiteralCompMatrN`) accept inline instantiations of 2D arrays, and don't require any every element therein to be a literal. Instead, these arrays can contain variables, arithmetic expressions, etc.
- removed `setStringCompMatrN` since it wouldn't flawlessly enable 2D array inline initialisation in C (without the compound literal syntax). Instead, it would restrict us to initialisations with only complex literals, precluding variables or arithmetic expressions
- added a compile-time size parameter to macro `setInlineCompMatr` necessary for C compatibility without the above mentioned limitations of stringifying the literal

tweaked CompMatrN initialisers

---

examples/matrices/initialisation.c
examples/matrices/initialisation.cpp

Tested with Clang and GNU, in C and C++, in MacOS and Ubuntu. We have not yet tested on Windows with MSVC which will almost definitely protest our use of C VLAs, requiring additional guards

added CompMatr examples

---

quest/include/environment.h
quest/include/qureg.h
quest/include/structures.h
quest/include/wrappers.h
quest/src/api/environment.cpp
quest/src/api/qureg.cpp
quest/src/api/structures.cpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/core/utilities.cpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

to improve defensive design, preventing users from mangling `Qureg`, `QuESTEnv` or `CompMatr` fields (except, I guess, if they really insisted upon it using `memcpy`)

made structs const

---

examples/matrices/initialisation.c
examples/matrices/initialisation.cpp
quest/include/structures.h
quest/src/api/structures.cpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/core/formatter.cpp
quest/src/core/formatter.hpp
quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp
quest/src/gpu/gpu_config.cpp
quest/src/gpu/gpu_config.hpp

and...
- changed 'elems' field of dynamic-size CompMatr to 'cpuElems' to better imply the need for synchronisation
- moved some matrix formatting logic into formatter.cpp, out of structures.cpp
- made matrix-creator free after failed validation to avoid memory leak
- disambiguated some validation naming

added DiagMatr

---

examples/matrices/initialisation.c
examples/matrices/initialisation.cpp
quest/include/structures.h
quest/src/api/structures.cpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/core/formatter.cpp
quest/src/core/formatter.hpp
quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp
quest/src/gpu/gpu_config.cpp
quest/src/gpu/gpu_config.hpp

to be more in-line with other variable-size heap objects, like Qureg (and the imminent PauliStrSum).
Further, N was an arbitrary suffix which didn't unambiguously identify an integer variable. N is a function which converts symbols to floating-point numbers in Mathematica, for example ;)
Now, CompMatr, which appears in many signatures (e.g. createCompMatr, destroyCompMatr), appears as the natural, general use type, as it should be. CompMatr1 and CompMatr2 are additionally constrained types (fixed sizes), reflected by their additional suffix, and which are stored in the stack.

removed N from CompMatrN

---

quest/src/api/environment.cpp
quest/src/api/initialisations.cpp
quest/src/api/qureg.cpp
quest/src/api/structures.cpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

by establishing a more consistent naming convention. Additionally moved Qureg-cleanup logic out of validation

tidied validation

---

quest/include/matrices.h
quest/include/operations.h
quest/include/quest.h
quest/src/api/matrices.cpp
quest/src/api/operations.cpp
quest/src/core/accelerator.cpp
quest/src/core/accelerator.hpp
quest/src/core/formatter.cpp
quest/src/core/formatter.hpp
quest/src/core/localiser.cpp
quest/src/core/localiser.hpp
quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/cpu/cpu_subroutines.hpp
quest/src/gpu/gpu_config.cpp
quest/src/gpu/gpu_config.hpp
quest/src/gpu/gpu_subroutines.cpp
quest/src/gpu/gpu_subroutines.hpp
scripts/compile.sh

since the CompMatr and DiagMatr code was together sufficiently substantial to warrant its own file.
Further data structures will be given their own files, or a file for their family, like paulis.h for PauliStr and PauliStrSum

renamed structures.h to matrices.h

---

examples/numbers/arithmetic.c
examples/numbers/arithmetic.cpp
quest/include/types.h
quest/include/wrappers.h
quest/src/api/types.cpp
quest/src/core/formatter.cpp
quest/src/core/formatter.hpp
scripts/compile.sh

in a precision agnostic fashion. This enables C and C++ users to perform arithmetic between qcomp and non-equal-precision numbers (like integers, non-qreal decimals, etc)
Other changes:
- added reportQcomp
- added arithmetic examples
- cleaned up formatter.cpp, overloading form_str to format complex numbers so that other core files can stringify complex numbers

added complex arithmetic

---

examples/matrices/initialisation.c
examples/matrices/initialisation.cpp
quest/include/matrices.h
quest/src/api/environment.cpp
quest/src/api/matrices.cpp
quest/src/api/qureg.cpp
quest/src/comm/comm_config.cpp
quest/src/comm/comm_config.hpp
quest/src/comm/comm_routines.cpp
quest/src/core/autodeployer.cpp
quest/src/core/autodeployer.hpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/core/formatter.cpp
quest/src/core/formatter.hpp
quest/src/core/memory.cpp
quest/src/core/memory.hpp
quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp
quest/src/cpu/cpu_config.cpp
quest/src/gpu/gpu_config.cpp
quest/src/gpu/gpu_config.hpp

and associated functions like
- createFullStateDiagMatr
- createCustomFullStateDiagMatr
- syncFullStateDiagMatr
- destroyFullStateDiagMatr
- setFullStateDiagMatr
- setInlineFullStateDiagMatr
- reportFullStateDiagMatr
Additionally:
- added validation that all heap-memory matrix types can fit into RAM and VRAM, and don't overflow index types, etc
- added FullStateDiagMatr auto-distributer
- updated matrix initialisation examples
- made all nodes free all memory if any node fails Qureg allocs
- added internal convenience comm_isRootNode()
- moved MPI types out of config header, into routines source, since they're never needed externally
- added internal matrix typing utilities

added FullStateDiagMatr

---

quest/include/debug.h
quest/include/matrices.h
quest/src/api/debug.cpp
quest/src/api/matrices.cpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

I was intending to bind field `.isUnitary` to large (heap-memory) matrices, assessed at runtime inside functions like `syncCompMatr()`. This would enable unitarity to be assessed _once_ before repeated application of a matrix to a `Qureg`, avoiding duplicate computation; especially worthwhile for full-state operators like `FullStateDiagMatr`. This would integrate nicely with the new validation toggle - when validation is off, `sync*()` would set `.isUnitarity = -1` to indicate it was unknown. If validation was later restored and that same matrix passed to a simulation function like `multiQubitUnitary()`, unitarity could be lazily evaluated at that moment, overwriting the matrix's field to preclude later repeated evaluation.
Alas, this isn't directly possible with a value (like `int`) …

accelerating matrix validation

---

examples/matrices/reporting.c
examples/matrices/reporting.cpp
quest/include/debug.h
quest/src/api/debug.cpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

so that it can be used to modulate the truncation of other reported structures

renamed to setNumReportedItems

---

examples/paulis/initialisation.c
examples/paulis/initialisation.cpp
quest/include/paulis.h
quest/src/api/paulis.cpp
quest/src/core/formatter.cpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

in addition to:
- patching memory reporting of `PauliStrSum`
- made signatures to accept `const char*` instead of `char*` for native support of C++ string literals
- tidying the cross-file function call between formatter and paulis

added Pauli examples

---

quest/include/modes.h
quest/include/precision.h
quest/src/api/environment.cpp
quest/src/comm/comm_config.cpp
quest/src/comm/comm_routines.cpp
quest/src/core/bitwise.hpp
quest/src/cpu/cpu_config.cpp
quest/src/gpu/gpu_config.cpp
quest/src/gpu/gpu_config.hpp
quest/src/gpu/gpu_cuquantum.hpp
quest/src/gpu/gpu_kernels.hpp
quest/src/gpu/gpu_subroutines.cpp
quest/src/gpu/gpu_thrust.hpp
quest/src/gpu/gpu_types.hpp
scripts/compile.sh

from:
- ENABLE_DISTRIBUTION
- ENABLE_MULTITHREADING
- ENABLE_GPU_ACCELERATION
- ENABLE_CUQUANTUM
to:
- COMPILE_MPI
- COMPILE_OPENMP
- COMPILE_CUDA
- COMPILE_CUQUANTUM
This is to better reflect their effect in-code since compiling the latter technologies does not necessitate the enabling of the corresponding deployments at runtime. For example, consider when the user compiles MPI but disables distribution when creating the QuESTEnv at runtime. In that scenario, the ENABLE_DISTRIBUTION precompiler guards are misleading; the user has NOT enabled distribution and so calling MPI API functions therein compiles but will throw an internal error at runtime (as happened during testing, inspiring this change).
We can abstract the nuances of compiling the deployment libraries from the user at …

renamed deployment macros

---

examples/matrices/initialisation.cpp
examples/paulis/initialisation.cpp
examples/reporters/paulis.cpp
quest/src/api/environment.cpp
quest/src/api/matrices.cpp
quest/src/api/paulis.cpp
quest/src/api/qureg.cpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/core/parser.cpp
quest/src/core/parser.hpp
quest/src/core/printer.cpp
quest/src/core/printer.hpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp
quest/src/gpu/gpu_cuquantum.hpp
quest/src/gpu/gpu_types.hpp

to remove std:: boilerplate everywhere, and to avoid recklessly including the entire std:: namespace in files parser.cpp and printer.cpp

tidied namespaces

---

quest/src/comm/comm_indices.hpp
quest/src/comm/comm_routines.cpp
quest/src/comm/comm_routines.hpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/core/localiser.cpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/cpu/cpu_subroutines.hpp
quest/src/gpu/gpu_kernels.hpp
quest/src/gpu/gpu_subroutines.cpp

so that the sent sub-buffers always begin in the middle of the full-buffer. This enables the communicated amplitudes to be received to the first index (zero), to be consistent with the scenario when sub-buffers are not packed (the buffer is filled straight from the Qureg amplitudes). As a result, post-communication subroutines always know where the received amplitudes begin in the buffer; from zero.
This is crucial; many post-communication routines are agnostic to the number of control qubits, and as a result, they do not know whether all amplitudes were exchanged (the buffer was filled entirely) or a sub-buffer was packed and exchanged. Before this change, the receiving index was inconsistent between these two situations, requiring the post-comm subroutine to condition on the number of …

changed communication buffer indexing

---

quest/src/api/matrices.cpp
quest/src/api/paulis.cpp
quest/src/api/qureg.cpp
quest/src/core/accelerator.cpp
quest/src/core/accelerator.hpp
quest/src/core/localiser.cpp
quest/src/cpu/cpu_config.cpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/gpu/gpu_kernels.hpp
quest/src/gpu/gpu_subroutines.cpp

- moved the final subroutine of `localiser_statevec_anyCtrlSwap()` into its own function so it can be directly called by `localiser_statevec_anyCtrlAnyTargDenseMatr()`, avoiding repeated, superfluous processing
- removed unnecessary non-`NULL` checks before `free()` (thanks @rrmeister !)
- reduced function-dispatch code duplication in `accelerator.cpp` using mOaR mACroS
- reduced thread-indexing code duplication in `gpu_kernels.hpp` using mOAr MacROs
- clarified `kernel_statevec_anyCtrlAnyTargDenseMatr_sub()` using some pretty inline functions
- moved instantiation macros of templated functions to the bottom of their sections for visual clarity

tidied boilerplate

---

quest/include/debug.h
quest/src/api/debug.cpp
quest/src/api/environment.cpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/gpu/gpu_config.cpp
quest/src/gpu/gpu_config.hpp
quest/src/gpu/gpu_subroutines.cpp

so that many-target CompMatr can be simulated without wastefully re-allocating thread-private global memory. This elevates commit https://github.com/QuEST-Kit/QuEST/commit/dd2b54993166390244fe3b45103edf41df8847a0 to be actually worthwhile.
In addition, we
- optimised CPU any-targ dense matrix by avoiding unnecessary vector re-initialisation during loop
- added user-facing clearGpuCache()
- added user-facing getGpuCacheSize()
- updated reportQuESTEnv() to report the current cache size
Co-Authored-By: Richard Meister <richardm.tug@gmail.com>

added persistent GPU cache

---

quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/gpu/gpu_kernels.cuh
quest/src/gpu/gpu_subroutines.cpp

by avoiding use of variables in OpenMP parallel regions which are unpacked from C++17 structured bindings, as per bug https://github.com/llvm/llvm-project/issues/33025

patched clang multithreading

---

quest/include/matrices.h
quest/src/api/matrices.cpp
quest/src/api/paulis.cpp
quest/src/api/qureg.cpp
quest/src/core/memory.cpp
quest/src/core/memory.hpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp
quest/src/gpu/gpu_config.cpp

All allocation checks have been moved to `memory.cpp` so that nullptr comparisons aren't littering the code, and to make explicit when nested data-structures are being thoroughly checked (i.e. that all nested pointers are non-NULL, vs just the outer). Also tidied/combined validation related to memory allocation.
Structures with persistent GPU memory now have a `wasGpuSynced` field to indicate whether their memory has ever been copied to the GPU since creation. This replaces the previously hacky design which kept the first GPU element as a special default value until being overwritten. That design necessitated wastefully copying (a single amplitude) from device to host at every invocation of "has synched" validation, which forces kernel synchronisation and precludes efficient streaming. …

refactored allocation and gpu-sync checks

---

examples/krausmaps/initialisation.c
examples/krausmaps/initialisation.cpp
examples/matrices/initialisation.c
examples/matrices/initialisation.cpp
examples/superoperators/initialisation.c
examples/superoperators/initialisation.cpp
quest/include/channels.h
quest/include/matrices.h
quest/src/api/channels.cpp
quest/src/api/matrices.cpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

specifically:
- createInlineKrausMap
- createInlineSuperOp
- createInlineCompMatr
- createInlineDiagMatr
for user convenience, and to deter them from making bugs by passing inconsistent compile-time parameters between the create() and set() functions

added inline struct creators

---

quest/include/deprecated.h
quest/include/operations.h
quest/include/precision.h
quest/include/quest.h
quest/src/api/operations.cpp
quest/src/gpu/gpu_thrust.cuh

via an optional header `deprecated.h`, which users can include with preprocessor `INCLUDE_DEPRECATED_FUNCTIONS=1`. Each invocation of a deprecated v3 function will issue a warning (unless disabled with `DISABLE_DEPRECATION_WARNINGS=1`), and be automatically substituted with a v4 function if possible.

added v3 deprecated functions

---

quest/include/channels.h
quest/include/environment.h
quest/include/matrices.h
quest/include/paulis.h
quest/include/qureg.h
quest/src/api/matrices.cpp

since this prevents users from maintaining collections of the structs, like arrays and vectors. Working around that limitation (e.g. the deletion of the default copy constructor in C++, or writing to read-only memory in C) is an enormous chore for the user, and well outweighs the benefit of preventing them from modifying the struct fields. We are anyway validation the fields are self consistent, so we will likely catch users mischievously modifying the fields

removed const struct fields

---

quest/include/deprecated.h
quest/include/matrices.h
quest/src/api/matrices.cpp
quest/src/core/bitwise.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

Specifically
- setDiagMatrFromMultiVarFunc
- setDiagMatrFromMultiDimLists
- setFullStateDiagMatrFromMultiVarFunc
- setFullStateDiagMatrFromMultiDimLists
These form the replacements of v3's numerous phase functions, generalised to support completely general functions, arbitrary amplitudes, significantly simplify the interface, preclude overrides, and generally be more efficient.
They permit Simon et. al. to specify arbitrary potentials in quantum Fourier split-step

added set(FullState)DiagMatrFromMulti*

---

quest/src/core/accelerator.cpp
quest/src/core/accelerator.hpp
quest/src/core/bitwise.hpp
quest/src/core/localiser.cpp
quest/src/core/localiser.hpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/cpu/cpu_subroutines.hpp
quest/src/gpu/gpu_cuquantum.cuh
quest/src/gpu/gpu_kernels.cuh
quest/src/gpu/gpu_subroutines.cpp
quest/src/gpu/gpu_subroutines.hpp
quest/src/gpu/gpu_types.cuh

We originally avoided these bespoke implementations because their communication and simulation logics are identical to the any-target cases, and likely too is their performance after templating. Alas, we had to implement them because of their different treatments/assumptions about GPU memory. The fixed-size matrices should avoid storing their data in global GPU memory, which is slower accessed by threads than kernel args, and requires pre-allocation. 
Without these bespoke implementations, we would have to create temporary heap-matrices when simulating user-given fixed-size matrices which is gross, tedious, and would lead to significant boilerplate in all the top-layer API functions which wrap fixed-size matrix calls (e.g. `applyHadamard()` maps to `1/sqrt(2) {{1,1},{1,-1}}`).

added fixed-size matrix backend functions

---

quest/include/debug.h
quest/src/api/debug.cpp
quest/src/api/qureg.cpp
quest/src/core/printer.cpp
quest/src/core/printer.hpp
quest/src/core/validation.cpp
quest/src/core/validation.hpp

through function setMaxNumReportedSigFigs, affecting all floating-point scalar reporting.
Also:
- changed reported memory unit from 'bytes' to most-convenient for the reported size
- added validation to debug utilities
- added validation to qureg sync utilities
- renamed validation epsilon global variable

added user-configurable sig-figs

---

quest/src/api/operations.cpp
quest/src/api/paulis.cpp
quest/src/core/accelerator.cpp
quest/src/core/accelerator.hpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/core/fastmath.hpp
quest/src/core/localiser.cpp
quest/src/core/localiser.hpp
quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/cpu/cpu_subroutines.hpp
quest/src/gpu/gpu_kernels.cuh
quest/src/gpu/gpu_subroutines.cpp
quest/src/gpu/gpu_subroutines.hpp

such that backend functions which apply Pauli tensors and gadgets are agnostic to whether simulation is distributed.
Previously, these functions received masks encoding Paulis even on the prefix substate, for which necessary pre-communication had already been performed. This violated the convention maintained by other backend functions to receive only suffix target qubits, and disrupted the modularity of communication and backend simulation. Now, the backend functions receive only suffix Paulis; the impact of the prefix Paulis is to change the complex coefficients passed to the backend.
This refactor involved removing the messy `util_pauliStrData` type.

refactored Paulis in backend

---

quest/src/api/operations.cpp

so that all v3 deprecated "operator" unit tests pass, for development convenience.
We will return to optimise a novel, optimised method (adapted from Simon's, removed from the initial distributed manuscript)

added placeholder QFT implementation

---

quest/include/operations.h
quest/include/precision.h
quest/include/wrappers.h
quest/src/api/calculations.cpp
quest/src/api/operations.cpp
quest/src/core/accelerator.cpp
quest/src/core/errors.cpp
quest/src/core/fastmath.hpp
quest/src/core/localiser.cpp
quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
quest/src/cpu/cpu_subroutines.cpp
quest/src/gpu/gpu_subroutines.cpp
quest/src/gpu/gpu_thrust.cuh

specifically:
-centralised localiser's struct spoofing
- added missing multiplyFullStateDiagMatrPower API declaration
- corrected `DEAULT_VALIDATION_EPSILON` typo (eep!)
- added calcExpecNonHermitianPauliStrSum definition, missing from https://github.com/QuEST-Kit/QuEST/commit/4621e89d6235b5a391e646d6eac5e7264a8f14e0
- patched applyQubitMeasurementAndGetProb which was not modifying output probability pointer
- patched initPureState validation
- changed nullptr comparisons in errors.cpp to use mem_isAllocated for consistency
- removed now-superfluous warning-suppressing code from cpu_subroutines
- improved some doc

misc tidying and v4 bug patches

---

quest/src/core/randomiser.cpp
scripts/compile.sh
tests/integration/placeholder.cpp
tests/main.cpp
tests/unit/calculations.cpp
tests/unit/decoherence.cpp
tests/unit/environment.cpp
tests/unit/initialisations.cpp
tests/unit/matrices.cpp
tests/unit/operations.cpp
tests/unit/paulis.cpp
tests/unit/qureg.cpp
tests/unit/types.cpp
tests/utils/compare.cpp
tests/utils/compare.hpp
tests/utils/convert.cpp
tests/utils/convert.hpp
tests/utils/evolve.cpp
tests/utils/evolve.hpp
tests/utils/linalg.cpp
tests/utils/linalg.hpp
tests/utils/lists.cpp
tests/utils/lists.hpp
tests/utils/macros.hpp
tests/utils/qmatrix.cpp
tests/utils/qmatrix.hpp
tests/utils/qvector.cpp
tests/utils/qvector.hpp
tests/utils/random.cpp
tests/utils/random.hpp

The v4 utility functions are refactored and significantly de-cluttered from v3, and separated into semantic files. The unit tests are also placed into a 'unit' subfolder, with an 'integration' subfolder reserved for future integration tests.
QMatrix and QVector respectively became qmatrix and qvector, and several functions were renamed (notably, areEqual() became a == overload).
These changes were motivated by the possibility of exposing testing utilities to users for use in their own C++ source, to leverage the convenient matrix algebra/overloads and random generators

Scaffolding v4 unit tests

---

cmake/FindCUQUANTUM.cmake

Apologies for PR spam 😅 
Spotted this while I was checking to see if I'd bothered to set `_FOUND` flags for the individual libraries. I haven't, but if for example you needed a specific minimum version of cuStateVec this could be split into three find project files rather than this monolithic cuQuantum one. 
All a bit messy of course because you can only download them as one...

FindCUQUANTUM.cmake: typo correction

---

quest/include/channels.h
quest/include/matrices.h
quest/src/api/channels.cpp
quest/src/api/matrices.cpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp
quest/src/cpu/cpu_config.cpp
quest/src/cpu/cpu_config.hpp
quest/src/gpu/gpu_config.cpp

replacing the 2D CPU memory of CompMatr and SuperOp, which each retain a 2D alias to the new 1D memory for user convenience.
Existing code which accesses .cpuElems of both these structs remains valid, although some usages may be accelerated by switching to accesing .cpuElemsFlat (like some unit-testing code).
Prompted by discussion #540

added row-major CPU matrices

---

CMakeLists.txt
quest/include/matrices.h
quest/src/api/operations.cpp
quest/src/core/bitwise.hpp
quest/src/core/localiser.cpp
quest/src/core/printer.cpp
quest/src/core/validation.cpp
tests/CMakeLists.txt
tests/utils/linalg.cpp
tests/utils/random.cpp

**Fixes #538**
This PR resolves compiler errors on MSVC by replacing non-standard usage of designated initializers combined with C-style casts. Previously, the code used:
```c++
return (CompMatr1) {
.numQubits = 1,
.numRows = 2,
.elems = {
{in[0][0], in[0][1]},
{in[1][0], in[1][1]}
}
};
```
which is incompatible with MSVC. The updated implementation ensures standard compliance by using:
```c++
CompMatr1 out = {
.numQubits = 1,
.numRows = 2,
.elems = {
{in[0][0], in[0][1]},
{in[1][0], in[1][1]}
}
};
return out;
```
Additionally, functions relying on GCC-specific intrinsics have been refactored to improve cross-compiler compatibility.
Attempting to build the v4 branch on Windows with MSVC resulted in the following errors:
```
E:\projects\QuEST\quest\include\matrices.h(220,9): error C7555: …
```

Fixing MSVC Compiler Errors

---

.github/workflows/compile.yml
CMakeLists.txt

Hi Tyson, 
Without wishing to traumatise you further, I thought I'd have a look into the AMD GPU CI failures, you were battling yesterday. I can't see any obvious fix unfortunately. One thing to try might be adding:
```
find_package(rocthrust REQUIRED)
target_link_libraries(QuEST PRIVATE roc::rocthrust)
```
however, when I tried that on A2 it a) broke the ability for us to compile the non-GPU code with anything but hipcc, as it adds the offload target flag everywhere, and b) lead to an unexpected link-time failure. 
It might be more interesting to just try `find_package(rocthrust REQUIRED)` to check that the build system does actually see that package _somewhere_. From brief inspection it looks like rocThrust is a header only template libary, so there shouldn't need to be any actual …

CMake: minor tweak to hip compilation

---

quest/include/channels.h
quest/src/api/channels.cpp
quest/src/api/debug.cpp
quest/src/api/matrices.cpp
quest/src/api/paulis.cpp
quest/src/core/utilities.cpp
quest/src/core/utilities.hpp
quest/src/core/validation.cpp
tests/unit/channels.cpp
tests/unit/debug.cpp
tests/unit/matrices.cpp
tests/unit/paulis.cpp
tests/unit/qureg.cpp

- renamed KrausMap.isCPTP to KrausMap.isApproxCPTP to reflect its epsilon-dependence, for consistency with isApproxUnitarity, isApproxHermitian and isApproxNonZero
- defined util_setFlagToUnknown() so that constant validate_STRUCT_PROPERTY_UNKNOWN_FLAG need not be exposed beyond validation.cpp and utilities.cpp
- renamed util_setEpsilonSensitiveStructFieldsToUnknown() to util_setEpsilonSensitiveHeapFlagsToUnknown() to be consistent with related utility functions util_(de)allocEpsilonSensitiveHeapFlag()
- made util_allocEpsilonSensitiveHeapFlag() update the ptr to validate_STRUCT_PROPERTY_UNKNOWN_FLAG by default, in case caller forgets to
- removed redundant logic from validation.cpp which checked whether KrausMap.isCPTP and PauliStrSum.isApproxHermitian were pre-set
- added tests to check …

tidied heap flags

---

quest/src/comm/comm_routines.cpp
quest/src/core/errors.cpp
quest/src/core/errors.hpp

By giving each send-recv pair a unique tag, we no longer require message orderedness and can ergo support adaptive routing (AR)

added MPI tags to support AR

---

tests/unit/operations.cpp

Ayyyyy 😎 
```
QuEST execution environment:
precision:       2
multithreaded:   1
distributed:     1
GPU-accelerated: 1
cuQuantum:       0
num nodes:       4
num qubits:      6
num qubit perms: 50
Tested Qureg deployments:
GPU + OMP + MPI
Randomness seeded to: 3254013672
===============================================================================
All tests passed (75364 assertions in 240 test cases)
```
As discussed in #581.

matrix sync tests: correct dereference of wasGpuSynced.
