QuEST-Kit/QuEST

QuEST/CPU/QuEST_cpu.c, QuEST/CPU/QuEST_cpu_local.c, QuEST/GPU/QuEST_gpu.cu, QuEST/QuEST.c, QuEST/QuEST.h, QuEST/QuEST_common.c, QuEST/QuEST_ops.h, QuEST/QuEST_precision.h, QuEST/QuEST_validation.c
I promise to indent by 4 spaces from now on :)
=> changed tab indentation to spaces

QuEST/CPU/QuEST_cpu.c, QuEST/CPU/QuEST_cpu_distributed.c, QuEST/CPU/QuEST_cpu_internal.h, QuEST/CPU/QuEST_cpu_local.c, QuEST/GPU/QuEST_gpu.cu, QuEST/QuEST.c, QuEST/QuEST.h, QuEST/QuEST_common.c, QuEST/QuEST_complex.h, QuEST/QuEST_debug.h, QuEST/QuEST_internal.h, QuEST/QuEST_ops.h, QuEST/QuEST_precision.h, QuEST/QuEST_qasm.c, QuEST/QuEST_qasm.h, QuEST/QuEST_validation.c, QuEST/QuEST_validation.h, examples/tutorial_example.c, tests/runTests.c
=> Adding optional precision-agnostic lingo-agnostic operator-overloaded complex type

QuEST/CMakeLists.txt, QuEST/src/GPU/QuEST_gpu.cu, examples/tutorial_example.c, tests/QuESTCore.py, tests/QuESTFunc.py, tests/QuESTTest.py, tests/QuESTTypes.py
Fixing errors made when merging PythonTesting into develop. Also restoring tutorial_example.c. 
Tested with:
OpenMP test: linux, gcc 6.5, 8 threads
GPU test: linux, compute capability 5.2, cuda 9, gcc 6.5
MPI test -- working on this -- there may be a problem with the MPI version. This pull request won't affect the MPI version
=> Bug fix build refactor

Utilities/QuESTTest/QuESTCore.py, Utilities/QuESTTest/__main__.py
Added Full log flag to log passes.
Fixed capitalisation of failed.
=> Requested changes to test logging

AUTHORS.txt, README.md, examples/makefile
Removed personal emails and added quest email address
=> removed personal emails and added quest email address

AUTHORS.txt, QuEST/include/QuEST.h, QuEST/src/CPU/QuEST_cpu.c, QuEST/src/CPU/QuEST_cpu_distributed.c, QuEST/src/CPU/QuEST_cpu_internal.h, QuEST/src/CPU/QuEST_cpu_local.c, QuEST/src/GPU/QuEST_gpu.cu, QuEST/src/QuEST.c, QuEST/src/QuEST_common.c, QuEST/src/QuEST_internal.h, QuEST/src/mainpage.h, README.md, examples/damping_example.c, tests/unit/density_matrix/noise/applyOneQubitDampingError.test, tests/unit/density_matrix/noise/applyOneQubitDephaseError.test, tests/unit/density_matrix/noise/applyOneQubitDepolariseError.test, tests/unit/density_matrix/noise/applyTwoQubitDephaseError.test, tests/unit/density_matrix/noise/applyTwoQubitDepolariseError.test, utilities/QuESTPy/QuESTFunc.py
=> Renaming decoherence functions

QuEST/include/QuEST.h, QuEST/src/GPU/QuEST_gpu.cu
added missing GPU implementation of `calcDensityInnerProduct`
=> Hilbert-Schmidt scalar product of density matrices (GPU)

QuEST/include/QuEST.h, QuEST/src/QuEST_common.c
so that current unit tests all run correctly
=> merging multiRotatePauli patch

QuEST/src/CPU/QuEST_cpu_distributed.c, QuEST/src/QuEST.c, QuEST/src/QuEST_validation.c, QuEST/src/QuEST_validation.h
Added additional validation triggered inside
- `createQuESTEnv`
- `createQureg`
- `createDensityQureg`
=> Improve validation

QuEST/include/QuEST.h, QuEST/include/QuEST_precision.h, QuEST/src/QuEST.c, QuEST/src/QuEST_common.c, QuEST/src/QuEST_internal.h, QuEST/src/QuEST_validation.c, QuEST/src/QuEST_validation.h, tests/test_calculations.cpp, tests/test_data_structures.cpp, tests/test_operators.cpp, tests/utilities.cpp, tests/utilities.hpp
=> adding support for Pauli Hamiltonians and Trotterisation

.github/workflows/llvm-asan.yml, QuEST/include/QuEST.h, QuEST/src/CPU/QuEST_cpu.c, QuEST/src/CPU/QuEST_cpu_distributed.c, QuEST/src/CPU/QuEST_cpu_local.c, QuEST/src/GPU/QuEST_gpu.cu
useful for interfacing projects, like [pyQuEST](https://github.com/rrmeister/pyQuEST)
=> added getEnvironmentString() 

QuEST/include/QuEST.h
since the new doc style has a white background, and no longer needs the (now, unattractive) border
=> removed border around doc circuit diagrams

QuEST/include/QuEST.h, QuEST/src/CPU/QuEST_cpu.c, QuEST/src/GPU/QuEST_gpu.cu, QuEST/src/QuEST.c, QuEST/src/QuEST_internal.h, QuEST/src/QuEST_validation.c, QuEST/src/QuEST_validation.h, tests/test_data_structures.cpp, tests/utilities.cpp, tests/utilities.hpp
=> diagonal operators from Pauli Hamiltonians

QuEST/src/CPU/QuEST_cpu.c
To make QuEST compatible with Microsoft Visual Studio, VLAs in `statevec_multiControlledMultiQubitUnitaryLocal()` had to be replaced with manually allocated memory on Windows. When doing this, the calls to `_malloca()` were performed outside the parallel block, where the VLAs are created. Unlike with VLAs, OpenMP does not automatically re-allocate the array memory for private pointers (`ampInds`, `reAmps`, `imAmps`) in each thread, resulting in invalid pointers in the parallel section. This commit moves memory allocation and deallocation into the parallel block, fixing the bug.
=> Fixed bug when compiled with MSVC

QuEST/src/CPU/QuEST_cpu_distributed.c
=> patched calcTotalProb (distributed & density matrix)

QuEST/CMakeLists.txt, QuEST/src/GPU/QuEST_gpu.cu, QuEST/src/GPU/cuda_to_hip.h, examples/README.md
* added header file with macros for cuda -> hip translation
* Updated CMakeLists.txt to support GPU compilation with HIP
* added brief instructions to build with HIP after the instructions to compile with GPU support.
=> Support for AMD GPUs  (#360)

QuEST/include/QuEST.h, QuEST/src/CPU/QuEST_cpu.c, QuEST/src/GPU/QuEST_gpu.cu, QuEST/src/QuEST_validation.c, tests/test_operators.cpp
Specifically `SCALED_INVERSE_SHIFTED_WEIGHTED_DISTANCE`
=> added weighted-distance phase function

QuEST/src/GPU/QuEST_cuQuantum.cu
Changed several operators represented by diagonal matrices but previously effected as one-qubit general matrices, to instead be effected as diagonals (duh)
=> optimised diagonal operators

quest/include/structures.h, quest/include/wrappers.h, quest/src/api/environment.cpp, quest/src/api/qureg.cpp, quest/src/api/structures.cpp, quest/src/core/formatter.cpp, quest/src/core/formatter.hpp, quest/src/core/memory.cpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp
Specifically:
- `CompMatr1`
- `CompMatr2`
- `CompMatrN`
with associated functions
- `getCompMatr1()`
- `getCompMatr2()`
- `createCompMatrN()`
- `destroyCompMatrN()`
- `reportCompMatr1()`
- `reportCompMatr2()`
- `reportCompMatrN()`
=> added CompMatr

quest/include/initialisations.h, quest/include/precision.h, quest/src/api/initialisations.cpp, quest/src/api/qureg.cpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp, quest/src/gpu/gpu_config.cpp, quest/src/gpu/gpu_config.hpp
- `initBlankState`
- `initZeroState`
- `initPlusState`
- `initClassicalState`
=> added some initialisations

examples/matrices/initialisation.cpp, examples/numbers/arithmetic.cpp, quest/include/types.h
to be precision agnostic, permitting mixing of literal precisions
=> extended complex arithmetic

quest/include/matrices.h, quest/src/api/environment.cpp, quest/src/api/paulis.cpp, quest/src/comm/comm_routines.cpp, quest/src/core/localiser.cpp, quest/src/core/memory.cpp, quest/src/core/parser.cpp, quest/src/core/printer.cpp, quest/src/core/utilities.cpp, quest/src/core/utilities.hpp, quest/src/core/validation.cpp, quest/src/gpu/gpu_cuquantum.hpp, quest/src/gpu/gpu_types.hpp, scripts/compile.sh
and updated recompile script to report them
=> fixed compiler warnings

quest/include/qureg.h, quest/src/api/qureg.cpp, quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/bitwise.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_cuquantum.cuh, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp
using Sec. V. D. [here](https://arxiv.org/pdf/2311.01512#page=35)
=> added dephasing

quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp
and tidied tidied localiser swaps into a single multi-swap function for easier later refactoring
=> added any-qubit partial-trace backend

quest/src/comm/comm_routines.cpp, quest/src/comm/comm_routines.hpp, quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_cuquantum.cuh, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp, quest/src/gpu/gpu_thrust.cuh, quest/src/gpu/gpu_types.cuh
which required substantial new communication, accelerator and GPU logic
=> added mixQureg backend

quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/core/utilities.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp, quest/src/gpu/gpu_types.cuh
which allow users to apply a diagonal operator raised to a power. Requested by Simon _et al_.
=> added apply-matrix-power backend functions

quest/src/comm/comm_routines.cpp, quest/src/comm/comm_routines.hpp, quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_config.cpp, quest/src/gpu/gpu_config.hpp, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp, quest/src/gpu/gpu_thrust.cuh
Special thanks to Antonio, Simona and Mike for permitting me workspace on the train :wink:
=> added FullStateDiagMatr backend functions

quest/src/api/calculations.cpp, quest/src/api/initialisations.cpp, quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/core/randomiser.cpp, quest/src/core/utilities.cpp, quest/src/core/utilities.hpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_thrust.cuh, quest/src/gpu/gpu_types.cuh
specifically:
- avoided modifying structs in accelerator (instead, created new copies as per defensive design)
- renamed and generalised some localiser utility functions
- renamed and generalised some validation functions
- renamed devicevec to devints in GPU backend (for subsequent generalisation)
- moved some calculations.cpp functions
- added TODOs in utilities for optimisations
=> cleaned code

quest/src/api/operations.cpp, quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp, quest/src/gpu/gpu_thrust.cuh
since used by conjugate-application of Pauli strings
=> added setQuregToSuperposition

quest/include/initialisations.h, quest/src/api/initialisations.cpp, quest/src/api/operations.cpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp, quest/src/gpu/gpu_thrust.cuh
and tweaked erroneous function names
=> added initRandomMixedState

quest/src/api/calculations.cpp, quest/src/api/operations.cpp, quest/src/api/paulis.cpp, quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/fastmath.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/core/utilities.cpp, quest/src/core/utilities.hpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_cuquantum.cuh, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp, quest/src/gpu/gpu_thrust.cuh
=> expectation values

quest/include/deprecated.h, quest/include/matrices.h, quest/include/operations.h, quest/src/api/initialisations.cpp, quest/src/api/matrices.cpp, quest/src/api/operations.cpp, quest/src/api/paulis.cpp, quest/src/core/accelerator.cpp, quest/src/core/accelerator.hpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/fastmath.hpp, quest/src/core/localiser.cpp, quest/src/core/localiser.hpp, quest/src/core/printer.cpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/cpu/cpu_subroutines.hpp, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_subroutines.hpp, quest/src/gpu/gpu_thrust.cuh
specifically:
- setQuregToPauliStrSum()
- setFullStateDiagMatrFromPauliStrSum()
- multiplyPauliStrSum()
- applyTrotterizedPauliStrSumGadget()
=> added remaining PauliStrSum functions

quest/include/calculations.h, quest/include/initialisations.h, quest/include/matrices.h, quest/include/qureg.h, quest/src/api/calculations.cpp, quest/src/api/environment.cpp, quest/src/api/initialisations.cpp, quest/src/api/matrices.cpp, quest/src/api/qureg.cpp, quest/src/core/accelerator.cpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp, quest/src/core/localiser.cpp, quest/src/core/validation.cpp, quest/src/core/validation.hpp
- calcPartialTrace
- calcReducedDensityMatrix
- setQuregToPartialTrace
- setQuregToReducedDensityMatrix
- setDensityQuregFlatAmps
- createFullStateDiagMatrFromPauliStrSum
- createForcedQureg
- createForcedDensityQureg
- getEnvironmentString
=> added remaining API functions

CMakeLists.txt, quest/include/operations.h, quest/src/api/calculations.cpp, quest/src/api/environment.cpp, quest/src/api/operations.cpp, quest/src/core/localiser.cpp, quest/src/core/printer.cpp, quest/src/core/utilities.cpp, quest/src/core/utilities.hpp, quest/src/core/validation.cpp, quest/src/cpu/cpu_config.cpp, quest/src/cpu/cpu_subroutines.cpp, quest/src/gpu/gpu_config.cpp, quest/src/gpu/gpu_config.hpp, quest/src/gpu/gpu_cuquantum.cuh, quest/src/gpu/gpu_kernels.cuh, quest/src/gpu/gpu_subroutines.cpp, quest/src/gpu/gpu_thrust.cuh
awaiting anticipated cuQuantum patches (testing on DiRAC)
=> more patches

.github/scripts/setup_cuda.ps1, .github/workflows/audit.yml, .github/workflows/compile.yml, .github/workflows/test.yml, CMakeLists.txt, quest/src/gpu/gpu_types.cuh
Fixes Windows GPU compilation issues. Tested on Win11 with an Nvidia 3080 Ti.
Sorry again 😅
=> Cmake windows

quest/src/comm/comm_routines.cpp, quest/src/core/errors.cpp, quest/src/core/errors.hpp
shout out to the Julia G's for helping discover the bug!
=> patching obtaining of MPI_TAG_UB

.github/workflows/doc.yml, .github/workflows/test_paid.yml, README.md
=> retriggering paid CI
